Feature/movement
alarson892/summer-23-unity pull request #4
Opened 2023-06-14 14:18 UTC by alarson892

Basic movement functionality

2023-06-14 19:46 UTC, clarson99 commented on summer-23-unity/Assets/Scripts/PlayerMovement.cs
> +            playerVelocity.y += Mathf.Sqrt(jumpHeight * -3.0f * gravityValue);
what is '-3.0f'?  Is that a magic constant?  It probably belongs up above with the other constants so i has a descriptive name.

2023-06-14 19:50 UTC, clarson99 requested changes
Can you fix the issue with the constant and add some docs about how you are doing movement?  Something like ./docs/movement.md would be a good start.

2023-06-15 01:48 UTC, alarson892 commented
Requested changes made

2023-06-15 02:20 UTC, clarson99 approved these changes
lgtm

2023-06-15 14:04 UTC, merged